var alternativesData = [
  {
    "id": "nasi-lemak-fried-chicken",
    "category": "rice",
    "keywords": ["nasi lemak", "nasi", "coconut rice"],
    "original": {
      "name": "Nasi Lemak with Fried Chicken",
      "emoji": "ðŸ›",
      "calories": 795,
      "protein": 38,
      "carbs": 62,
      "fat": 43,
      "saturatedFat": 18,
      "sugar": 5,
      "sodium": 980,
      "fibre": 2,
      "source": "HPB Singapore / HealthXchange.sg"
    },
    "alternative": {
      "name": "Grilled Chicken Breast with Brown Rice & Vegetables",
      "emoji": "ðŸ¥™",
      "calories": 420,
      "protein": 38,
      "carbs": 45,
      "fat": 10,
      "saturatedFat": 2.5,
      "sugar": 3,
      "sodium": 480,
      "fibre": 5,
      "source": "HPB Singapore / USDA FoodData Central"
    },
    "explanation": "This swap saves 375 kcal while keeping the same protein content. Total fat drops by 33g and saturated fat by 15.5g, significantly reducing heart disease risk. Brown rice adds 3g more fibre for better digestion, and sodium is halved â€” important since the average Singaporean already exceeds daily sodium limits."
  },
  {
    "id": "fried-rice",
    "category": "rice",
    "keywords": ["fried rice", "nasi goreng"],
    "original": {
      "name": "Fried Rice (Hawker)",
      "emoji": "ðŸ³",
      "calories": 607,
      "protein": 15,
      "carbs": 78,
      "fat": 25,
      "saturatedFat": 8,
      "sugar": 4,
      "sodium": 1120,
      "fibre": 2,
      "source": "HPB Singapore Food Composition Database"
    },
    "alternative": {
      "name": "Steamed Brown Rice with Stir-Fried Vegetables",
      "emoji": "ðŸ¥¦",
      "calories": 340,
      "protein": 9,
      "carbs": 58,
      "fat": 8,
      "saturatedFat": 1.5,
      "sugar": 4,
      "sodium": 420,
      "fibre": 6,
      "source": "HPB Singapore / USDA FoodData Central"
    },
    "explanation": "Saves 267 kcal by switching from wok-fried to steamed rice. Fat drops by 17g and saturated fat by 6.5g since stir-frying uses minimal oil. Sodium is reduced by 700mg â€” almost a third of the daily limit. The extra 4g of fibre from brown rice and vegetables helps maintain steady blood sugar levels."
  },
  {
    "id": "chicken-rice-roasted",
    "category": "rice",
    "keywords": ["chicken rice", "roasted chicken"],
    "original": {
      "name": "Chicken Rice (Roasted)",
      "emoji": "ðŸ—",
      "calories": 607,
      "protein": 27,
      "carbs": 68,
      "fat": 23,
      "saturatedFat": 8.5,
      "sugar": 2,
      "sodium": 890,
      "fibre": 1,
      "source": "HPB Singapore / NutriKaki (aligned with HealthXchange.sg)"
    },
    "alternative": {
      "name": "Steamed Chicken Breast with Plain Rice & Cucumber",
      "emoji": "ðŸ¥’",
      "calories": 440,
      "protein": 35,
      "carbs": 55,
      "fat": 8,
      "saturatedFat": 2,
      "sugar": 1,
      "sodium": 520,
      "fibre": 1.5,
      "source": "HPB Singapore / USDA FoodData Central"
    },
    "explanation": "Switching to steamed chicken saves 167 kcal and cuts fat by 15g. Removing the oily chicken skin eliminates most saturated fat (down 6.5g). Protein actually increases by 8g since skinless breast is leaner muscle. Sodium drops by 370mg as steamed preparation needs less seasoning."
  },
  {
    "id": "chicken-biryani",
    "category": "rice",
    "keywords": ["biryani", "briyani"],
    "original": {
      "name": "Chicken Biryani",
      "emoji": "ðŸ›",
      "calories": 740,
      "protein": 32,
      "carbs": 72,
      "fat": 35,
      "saturatedFat": 12,
      "sugar": 4,
      "sodium": 1250,
      "fibre": 3,
      "source": "HPB Singapore / HealthXchange.sg (Malay Hawker Foods)"
    },
    "alternative": {
      "name": "Grilled Chicken with Jeera Rice & Raita",
      "emoji": "ðŸ¥—",
      "calories": 445,
      "protein": 33,
      "carbs": 50,
      "fat": 12,
      "saturatedFat": 3.5,
      "sugar": 4,
      "sodium": 620,
      "fibre": 2,
      "source": "USDA FoodData Central / HPB Singapore"
    },
    "explanation": "This swap saves 295 kcal and cuts fat by 23g. Saturated fat drops dramatically (8.5g less) since biryani is cooked in ghee, while jeera rice uses minimal oil. Sodium reduction of 630mg is significant â€” biryani often exceeds half the daily sodium allowance in a single serving. Raita adds probiotics for gut health."
  },
  {
    "id": "mee-goreng",
    "category": "noodles",
    "keywords": ["mee goreng", "fried noodles", "fried mee", "mee"],
    "original": {
      "name": "Mee Goreng",
      "emoji": "ðŸœ",
      "calories": 550,
      "protein": 16,
      "carbs": 68,
      "fat": 24,
      "saturatedFat": 8,
      "sugar": 8,
      "sodium": 1450,
      "fibre": 3,
      "source": "HPB Singapore Food Composition Database"
    },
    "alternative": {
      "name": "Soup Noodles with Lean Chicken & Vegetables",
      "emoji": "ðŸ²",
      "calories": 350,
      "protein": 28,
      "carbs": 42,
      "fat": 7,
      "saturatedFat": 2,
      "sugar": 3,
      "sodium": 850,
      "fibre": 3,
      "source": "HPB Singapore / USDA FoodData Central"
    },
    "explanation": "Saves 200 kcal by switching from stir-fried to soup-based noodles. Fat drops by 17g and saturated fat by 6g. Protein increases by 12g with lean chicken, keeping you full longer. Sodium is still reduced by 600mg, and the broth-based format provides better hydration."
  },
  {
    "id": "char-kway-teow",
    "category": "noodles",
    "keywords": ["char kway teow", "kway teow", "ckw"],
    "original": {
      "name": "Char Kway Teow",
      "emoji": "ðŸ",
      "calories": 744,
      "protein": 20,
      "carbs": 82,
      "fat": 37,
      "saturatedFat": 14,
      "sugar": 5,
      "sodium": 1680,
      "fibre": 2,
      "source": "NutriKaki / HPB Singapore / Singapore Heart Foundation"
    },
    "alternative": {
      "name": "Kway Teow Soup with Fish Slices",
      "emoji": "ðŸœ",
      "calories": 330,
      "protein": 26,
      "carbs": 42,
      "fat": 6,
      "saturatedFat": 1.5,
      "sugar": 2,
      "sodium": 780,
      "fibre": 1,
      "source": "HPB Singapore / HealthXchange.sg"
    },
    "explanation": "This is one of the biggest calorie savings â€” 414 kcal less. Char kway teow is cooked with lard and dark soy sauce, giving it extremely high fat (37g) and sodium (1680mg). The soup version eliminates lard entirely, cutting saturated fat by 12.5g. Fish provides lean protein with omega-3 fatty acids for heart health."
  },
  {
    "id": "curry-laksa",
    "category": "noodles",
    "keywords": ["laksa", "curry noodles"],
    "original": {
      "name": "Curry Laksa",
      "emoji": "ðŸœ",
      "calories": 613,
      "protein": 22,
      "carbs": 60,
      "fat": 32,
      "saturatedFat": 18,
      "sugar": 5,
      "sodium": 1520,
      "fibre": 3,
      "source": "NutriKaki / HPB Singapore"
    },
    "alternative": {
      "name": "Asam Laksa (Sour Fish Soup Noodles)",
      "emoji": "ðŸ¥£",
      "calories": 380,
      "protein": 22,
      "carbs": 52,
      "fat": 9,
      "saturatedFat": 2,
      "sugar": 6,
      "sodium": 920,
      "fibre": 3,
      "source": "HPB Singapore / Malaysian Food Composition Database"
    },
    "explanation": "Saves 233 kcal by replacing coconut milk broth with tamarind-based soup. The massive drop in saturated fat (16g less) is the key benefit â€” coconut milk is one of the highest sources of saturated fat in hawker food. Sodium is also reduced by 600mg while protein stays the same."
  },
  {
    "id": "instant-noodles",
    "category": "noodles",
    "keywords": ["instant noodles", "maggi", "cup noodle"],
    "original": {
      "name": "Instant Noodles (with seasoning)",
      "emoji": "ðŸœ",
      "calories": 460,
      "protein": 9,
      "carbs": 58,
      "fat": 20,
      "saturatedFat": 9,
      "sugar": 4,
      "sodium": 1580,
      "fibre": 2,
      "source": "USDA FoodData Central / Manufacturer nutrition labels"
    },
    "alternative": {
      "name": "Rice Vermicelli Soup with Egg & Vegetables",
      "emoji": "ðŸ²",
      "calories": 280,
      "protein": 14,
      "carbs": 38,
      "fat": 7,
      "saturatedFat": 2,
      "sugar": 3,
      "sodium": 650,
      "fibre": 3,
      "source": "USDA FoodData Central / HPB Singapore"
    },
    "explanation": "Saves 180 kcal. Instant noodles are deep-fried during manufacturing (9g saturated fat) and the seasoning packet alone contains ~1000mg sodium. The fresh alternative cuts sodium by 930mg and saturated fat by 7g. The egg adds quality protein (14g vs 9g) to keep you fuller."
  },
  {
    "id": "big-mac-fries",
    "category": "fast-food",
    "keywords": ["burger", "fast food", "fries", "mcdonalds", "big mac"],
    "original": {
      "name": "McDonald's Big Mac + Medium Fries",
      "emoji": "ðŸ”",
      "calories": 900,
      "protein": 29,
      "carbs": 87,
      "fat": 48,
      "saturatedFat": 16,
      "sugar": 12,
      "sodium": 1340,
      "fibre": 5,
      "source": "McDonald's Singapore Nutrition Information (2024)"
    },
    "alternative": {
      "name": "Grilled Chicken Wrap with Side Salad",
      "emoji": "ðŸ¥ª",
      "calories": 460,
      "protein": 32,
      "carbs": 45,
      "fat": 15,
      "saturatedFat": 4,
      "sugar": 5,
      "sodium": 780,
      "fibre": 5,
      "source": "McDonald's Singapore / Subway Singapore Nutrition Data"
    },
    "explanation": "Saves 440 kcal â€” nearly half the calories. A Big Mac alone is 580 kcal; adding medium fries brings it to 900. The wrap provides more protein (32g vs 29g) with dramatically less fat (33g less) and saturated fat (12g less). Sodium drops by 560mg, and sugar is reduced by 7g from the fries and bun."
  },
  {
    "id": "pizza-pepperoni",
    "category": "fast-food",
    "keywords": ["pizza", "pepperoni", "pizza hut", "dominos"],
    "original": {
      "name": "Pepperoni Pizza (2 slices, regular)",
      "emoji": "ðŸ•",
      "calories": 568,
      "protein": 22,
      "carbs": 56,
      "fat": 28,
      "saturatedFat": 12,
      "sugar": 6,
      "sodium": 1240,
      "fibre": 3,
      "source": "Pizza Hut Singapore / Domino's Nutrition Information"
    },
    "alternative": {
      "name": "Whole Wheat Pita with Grilled Vegetables & Hummus",
      "emoji": "ðŸ¥™",
      "calories": 320,
      "protein": 12,
      "carbs": 42,
      "fat": 12,
      "saturatedFat": 2,
      "sugar": 5,
      "sodium": 520,
      "fibre": 8,
      "source": "USDA FoodData Central"
    },
    "explanation": "Saves 248 kcal and dramatically cuts saturated fat (10g less) from cheese and processed pepperoni. Sodium drops by 720mg â€” two slices of pizza already provide over half the daily sodium limit. Fibre increases by 5g from whole wheat pita and vegetables, promoting better digestion and satiety."
  },
  {
    "id": "fried-chicken-2pc",
    "category": "fast-food",
    "keywords": ["fried chicken", "kfc", "popeyes", "texas chicken"],
    "original": {
      "name": "Fried Chicken (2 pieces, Original Recipe)",
      "emoji": "ðŸ—",
      "calories": 640,
      "protein": 50,
      "carbs": 20,
      "fat": 40,
      "saturatedFat": 10,
      "sugar": 0,
      "sodium": 1220,
      "fibre": 1,
      "source": "KFC Singapore Nutrition Information"
    },
    "alternative": {
      "name": "Grilled Chicken Thigh with Coleslaw",
      "emoji": "ðŸ¥—",
      "calories": 380,
      "protein": 35,
      "carbs": 12,
      "fat": 18,
      "saturatedFat": 4,
      "sugar": 5,
      "sodium": 580,
      "fibre": 2,
      "source": "USDA FoodData Central / HPB Singapore"
    },
    "explanation": "Saves 260 kcal by eliminating the deep-fried batter coating. Fat drops by 22g and saturated fat by 6g. While protein is slightly lower (35g vs 50g), it's still an excellent amount per meal. Sodium is halved (640mg less) since KFC's seasoning is very sodium-dense. Coleslaw adds fibre and vitamins."
  },
  {
    "id": "hotdog",
    "category": "fast-food",
    "keywords": ["hotdog", "hot dog", "sausage"],
    "original": {
      "name": "Hotdog with Sauces & Bun",
      "emoji": "ðŸŒ­",
      "calories": 425,
      "protein": 14,
      "carbs": 38,
      "fat": 24,
      "saturatedFat": 9,
      "sugar": 7,
      "sodium": 1050,
      "fibre": 1,
      "source": "USDA FoodData Central"
    },
    "alternative": {
      "name": "Turkey Sausage in Lettuce Wrap",
      "emoji": "ðŸ¥¬",
      "calories": 200,
      "protein": 20,
      "carbs": 4,
      "fat": 10,
      "saturatedFat": 3,
      "sugar": 2,
      "sodium": 520,
      "fibre": 1,
      "source": "USDA FoodData Central"
    },
    "explanation": "Saves 225 kcal by using turkey sausage (leaner meat) and lettuce instead of a refined white bun. Fat is cut by 14g and saturated fat by 6g. Sodium drops by 530mg â€” processed hotdog meat is one of the highest sodium fast foods. Protein increases by 6g for better muscle support."
  },
  {
    "id": "roti-prata",
    "category": "breakfast",
    "keywords": ["roti prata", "prata", "roti"],
    "original": {
      "name": "Roti Prata with Curry (2 pieces)",
      "emoji": "ðŸ«“",
      "calories": 520,
      "protein": 12,
      "carbs": 60,
      "fat": 26,
      "saturatedFat": 12,
      "sugar": 3,
      "sodium": 680,
      "fibre": 2,
      "source": "HPB Singapore / HealthXchange.sg (Indian Breads)"
    },
    "alternative": {
      "name": "Thosai with Sambar & Coconut Chutney",
      "emoji": "ðŸ¥ž",
      "calories": 250,
      "protein": 10,
      "carbs": 40,
      "fat": 5,
      "saturatedFat": 1.5,
      "sugar": 3,
      "sodium": 380,
      "fibre": 4,
      "source": "HPB Singapore / HealthXchange.sg"
    },
    "explanation": "Saves 270 kcal. Prata dough is kneaded with ghee and pan-fried, giving it 26g fat and 12g saturated fat. Thosai is a fermented rice-lentil crepe cooked with minimal oil, cutting fat by 21g. Sambar provides lentil-based fibre (4g vs 2g) and the fermentation improves nutrient absorption."
  },
  {
    "id": "nasi-lemak-breakfast",
    "category": "breakfast",
    "keywords": ["nasi lemak breakfast", "heavy breakfast"],
    "original": {
      "name": "Nasi Lemak Set (Breakfast)",
      "emoji": "ðŸ›",
      "calories": 644,
      "protein": 18,
      "carbs": 85,
      "fat": 27,
      "saturatedFat": 14,
      "sugar": 4,
      "sodium": 860,
      "fibre": 2,
      "source": "HPB Singapore / SnapCalorie"
    },
    "alternative": {
      "name": "Overnight Oats with Banana & Peanut Butter",
      "emoji": "ðŸ¥£",
      "calories": 380,
      "protein": 14,
      "carbs": 52,
      "fat": 14,
      "saturatedFat": 3,
      "sugar": 16,
      "sodium": 150,
      "fibre": 7,
      "source": "USDA FoodData Central"
    },
    "explanation": "Saves 264 kcal and more than halves the fat (13g less). Saturated fat drops by 11g â€” coconut milk rice is a major contributor. Sodium is dramatically reduced (710mg less). Oats provide 7g fibre for sustained energy and better blood sugar control throughout the morning. Note: sugar is higher due to natural banana sweetness, but it's unrefined."
  },
  {
    "id": "croissant",
    "category": "breakfast",
    "keywords": ["croissant", "pastry breakfast"],
    "original": {
      "name": "Butter Croissant",
      "emoji": "ðŸ¥",
      "calories": 340,
      "protein": 7,
      "carbs": 38,
      "fat": 18,
      "saturatedFat": 10,
      "sugar": 7,
      "sodium": 320,
      "fibre": 1.5,
      "source": "USDA FoodData Central"
    },
    "alternative": {
      "name": "Whole Wheat Toast with Avocado & Egg",
      "emoji": "ðŸ¥‘",
      "calories": 290,
      "protein": 14,
      "carbs": 26,
      "fat": 16,
      "saturatedFat": 3.5,
      "sugar": 2,
      "sodium": 380,
      "fibre": 6,
      "source": "USDA FoodData Central"
    },
    "explanation": "Saves 50 kcal but the real benefit is nutritional quality. Protein doubles (14g vs 7g) from the egg. Saturated fat drops by 6.5g since croissants are made with butter layers. Fibre increases by 4.5g from whole wheat and avocado. The healthy monounsaturated fats in avocado support heart health unlike butter's saturated fats."
  },
  {
    "id": "potato-chips",
    "category": "snacks",
    "keywords": ["chips", "potato chips", "crisps"],
    "original": {
      "name": "Potato Chips (1 bag, 60g)",
      "emoji": "ðŸ¥”",
      "calories": 320,
      "protein": 4,
      "carbs": 30,
      "fat": 20,
      "saturatedFat": 6,
      "sugar": 1,
      "sodium": 480,
      "fibre": 2,
      "source": "USDA FoodData Central / Manufacturer labels"
    },
    "alternative": {
      "name": "Air-Popped Popcorn (lightly salted, 30g)",
      "emoji": "ðŸ¿",
      "calories": 120,
      "protein": 4,
      "carbs": 22,
      "fat": 2,
      "saturatedFat": 0.3,
      "sugar": 0,
      "sodium": 180,
      "fibre": 4,
      "source": "USDA FoodData Central"
    },
    "explanation": "Saves 200 kcal with the same satisfying crunch. Fat plummets from 20g to just 2g since air-popping uses no oil. Saturated fat nearly disappears (5.7g less). Popcorn is a whole grain with double the fibre (4g vs 2g), and sodium drops by 300mg. Same snack satisfaction with a fraction of the damage."
  },
  {
    "id": "curry-puff",
    "category": "snacks",
    "keywords": ["curry puff", "goreng pisang", "fried snack"],
    "original": {
      "name": "Curry Puff (2 pieces)",
      "emoji": "ðŸ¥Ÿ",
      "calories": 440,
      "protein": 8,
      "carbs": 42,
      "fat": 28,
      "saturatedFat": 12,
      "sugar": 4,
      "sodium": 620,
      "fibre": 2,
      "source": "HPB Singapore Food Composition Database"
    },
    "alternative": {
      "name": "Steamed Chicken Pau (1 piece)",
      "emoji": "ðŸ¥Ÿ",
      "calories": 220,
      "protein": 10,
      "carbs": 30,
      "fat": 6,
      "saturatedFat": 2,
      "sugar": 4,
      "sodium": 380,
      "fibre": 1,
      "source": "HPB Singapore Food Composition Database"
    },
    "explanation": "Saves 220 kcal by switching from deep-fried pastry to steamed bun. Fat is cut by 22g and saturated fat by 10g â€” curry puffs absorb significant oil during frying. Protein increases by 2g from the chicken filling. Sodium drops by 240mg. Same satisfying savoury snack without the fried guilt."
  },
  {
    "id": "chocolate-bar",
    "category": "snacks",
    "keywords": ["chocolate", "candy", "sweets"],
    "original": {
      "name": "Chocolate Bar (50g)",
      "emoji": "ðŸ«",
      "calories": 265,
      "protein": 4,
      "carbs": 30,
      "fat": 15,
      "saturatedFat": 9,
      "sugar": 25,
      "sodium": 50,
      "fibre": 1,
      "source": "USDA FoodData Central (milk chocolate)"
    },
    "alternative": {
      "name": "Dark Chocolate (20g, 70%+) with Almonds (15g)",
      "emoji": "ðŸ¥œ",
      "calories": 185,
      "protein": 5,
      "carbs": 12,
      "fat": 14,
      "saturatedFat": 5,
      "sugar": 8,
      "sodium": 5,
      "fibre": 3,
      "source": "USDA FoodData Central"
    },
    "explanation": "Saves 80 kcal and dramatically cuts sugar (17g less). Dark chocolate has less sugar and more antioxidants (flavonoids) than milk chocolate. Saturated fat drops by 4g. Almonds add plant protein, healthy fats, vitamin E, and 2g more fibre. The combination is more satiating in smaller portions."
  },
  {
    "id": "bubble-tea",
    "category": "drinks",
    "keywords": ["bubble tea", "boba", "milk tea"],
    "original": {
      "name": "Bubble Tea (Large, Full Sugar with Pearls)",
      "emoji": "ðŸ§‹",
      "calories": 440,
      "protein": 2,
      "carbs": 88,
      "fat": 8,
      "saturatedFat": 5,
      "sugar": 55,
      "sodium": 80,
      "fibre": 0,
      "source": "HPB Singapore / NIH PubMed Study on Boba Beverages"
    },
    "alternative": {
      "name": "Iced Green Tea (0% sugar) with Aloe Vera",
      "emoji": "ðŸµ",
      "calories": 60,
      "protein": 0,
      "carbs": 14,
      "fat": 0,
      "saturatedFat": 0,
      "sugar": 8,
      "sodium": 10,
      "fibre": 1,
      "source": "USDA FoodData Central / Manufacturer labels"
    },
    "explanation": "Saves a massive 380 kcal â€” almost an entire meal's worth. Sugar drops from 55g to just 8g (47g less). A large bubble tea with full sugar exceeds the WHO daily added sugar limit (25g) in a single drink. The green tea alternative provides antioxidants (catechins) with aloe vera for texture, at near-zero fat."
  },
  {
    "id": "kopi-teh",
    "category": "drinks",
    "keywords": ["kopi", "coffee", "teh", "tea", "milo"],
    "original": {
      "name": "Kopi / Teh with Condensed Milk",
      "emoji": "â˜•",
      "calories": 135,
      "protein": 3,
      "carbs": 20,
      "fat": 5,
      "saturatedFat": 3,
      "sugar": 18,
      "sodium": 45,
      "fibre": 0,
      "source": "HPB Singapore / NutriKaki"
    },
    "alternative": {
      "name": "Kopi-O Kosong / Teh-O Kosong (no sugar)",
      "emoji": "ðŸµ",
      "calories": 8,
      "protein": 0,
      "carbs": 1,
      "fat": 0,
      "saturatedFat": 0,
      "sugar": 0,
      "sodium": 5,
      "fibre": 0,
      "source": "HPB Singapore / USDA FoodData Central"
    },
    "explanation": "Saves 127 kcal per cup â€” if you drink 3 cups daily, that's 381 kcal saved. Eliminating condensed milk removes all 18g of added sugar and 5g of fat. Over a week, switching from kopi to kopi-o kosong saves nearly 2,700 kcal â€” equivalent to a full day's food intake. Same caffeine, zero empty calories."
  },
  {
    "id": "soft-drink",
    "category": "drinks",
    "keywords": ["soda", "soft drink", "coke", "sprite", "fanta"],
    "original": {
      "name": "Soft Drink (330ml can)",
      "emoji": "ðŸ¥¤",
      "calories": 140,
      "protein": 0,
      "carbs": 36,
      "fat": 0,
      "saturatedFat": 0,
      "sugar": 36,
      "sodium": 30,
      "fibre": 0,
      "source": "Coca-Cola Singapore Nutrition Label"
    },
    "alternative": {
      "name": "Sparkling Water with Lemon Slice",
      "emoji": "ðŸ’§",
      "calories": 5,
      "protein": 0,
      "carbs": 1,
      "fat": 0,
      "saturatedFat": 0,
      "sugar": 0,
      "sodium": 20,
      "fibre": 0,
      "source": "USDA FoodData Central"
    },
    "explanation": "Saves 135 kcal of pure empty calories. Eliminates 36g of sugar â€” nearly 1.5 times the WHO recommended daily limit of 25g in a single can. Sparkling water provides the same fizzy, refreshing sensation with zero sugar. The lemon adds vitamin C and natural flavour without any caloric cost."
  },
  {
    "id": "ice-cream",
    "category": "desserts",
    "keywords": ["ice cream", "gelato"],
    "original": {
      "name": "Ice Cream (2 scoops, vanilla)",
      "emoji": "ðŸ¦",
      "calories": 370,
      "protein": 5,
      "carbs": 40,
      "fat": 22,
      "saturatedFat": 13,
      "sugar": 34,
      "sodium": 100,
      "fibre": 0,
      "source": "USDA FoodData Central (regular vanilla ice cream)"
    },
    "alternative": {
      "name": "Greek Yogurt with Fresh Berries & Honey",
      "emoji": "ðŸ“",
      "calories": 180,
      "protein": 15,
      "carbs": 24,
      "fat": 4,
      "saturatedFat": 2,
      "sugar": 18,
      "sodium": 60,
      "fibre": 2,
      "source": "USDA FoodData Central"
    },
    "explanation": "Saves 190 kcal and triples the protein (15g vs 5g). Fat drops by 18g and saturated fat by 11g â€” ice cream is one of the highest saturated fat desserts. Sugar is nearly halved (16g less), and the remaining sugar is from natural fruit and honey. Greek yogurt adds probiotics for gut health and calcium for bones."
  },
  {
    "id": "cake-slice",
    "category": "desserts",
    "keywords": ["cake", "cheesecake", "pastry"],
    "original": {
      "name": "Slice of Chocolate Cake",
      "emoji": "ðŸ°",
      "calories": 420,
      "protein": 5,
      "carbs": 52,
      "fat": 22,
      "saturatedFat": 10,
      "sugar": 38,
      "sodium": 320,
      "fibre": 2,
      "source": "USDA FoodData Central"
    },
    "alternative": {
      "name": "Chia Seed Pudding with Berries",
      "emoji": "ðŸ«",
      "calories": 190,
      "protein": 7,
      "carbs": 22,
      "fat": 9,
      "saturatedFat": 1.5,
      "sugar": 10,
      "sodium": 50,
      "fibre": 10,
      "source": "USDA FoodData Central"
    },
    "explanation": "Saves 230 kcal and slashes sugar by 28g. Saturated fat drops by 8.5g (cake frosting is butter-heavy). The standout benefit is fibre: chia seeds provide 10g vs just 2g, promoting fullness and digestive health. Chia seeds also contain omega-3 fatty acids and are naturally sweetened with berries instead of refined sugar."
  },
  {
    "id": "glazed-donut",
    "category": "desserts",
    "keywords": ["donut", "doughnut"],
    "original": {
      "name": "Glazed Donut",
      "emoji": "ðŸ©",
      "calories": 340,
      "protein": 4,
      "carbs": 42,
      "fat": 18,
      "saturatedFat": 8,
      "sugar": 22,
      "sodium": 280,
      "fibre": 1,
      "source": "USDA FoodData Central"
    },
    "alternative": {
      "name": "Banana Oat Muffin (homemade)",
      "emoji": "ðŸ§",
      "calories": 180,
      "protein": 5,
      "carbs": 28,
      "fat": 6,
      "saturatedFat": 1,
      "sugar": 12,
      "sodium": 150,
      "fibre": 3,
      "source": "USDA FoodData Central (calculated from recipe)"
    },
    "explanation": "Saves 160 kcal. A donut is deep-fried and glazed with sugar syrup, giving 18g fat and 22g sugar. The oat muffin cuts fat by 12g and sugar by 10g. Oats provide slow-release energy (low GI) keeping you full longer. Banana adds natural sweetness and potassium, eliminating the need for refined sugar."
  }
];